// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/app/server/registry"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/hashicorp/consul/api"
	"github.com/hertz-contrib/registry/consul"
	"yima_user_app/dao"
)

func main() {

	dao.DatabaseInit()
	config := api.DefaultConfig()
	config.Address = "127.0.0.1:8500"
	client, err := api.NewClient(config)
	if err != nil {
		panic(err)
	}
	r := consul.NewConsulRegister(client)
	h := server.Default(
		server.WithHostPorts("127.0.0.1:38000"),
		server.WithRegistry(r, &registry.Info{
			ServiceName: "yima.demo.user",
			Addr:        utils.NewNetAddr("tcp", "127.0.0.1:38000"),
			Weight:      1,
			Tags:        nil,
		}),
	)

	register(h)
	h.Spin()
}
