// Code generated by hertz generator.

package main

import (
	"git.horsecoder.com/chenpeiran/yima.demo.user/kitex_gen/yima/demo/user/yimademouser"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/app/server/registry"
	"github.com/cloudwego/hertz/pkg/common/utils"
	registry2 "github.com/cloudwego/kitex/pkg/registry"
	kserver "github.com/cloudwego/kitex/server"
	"github.com/hashicorp/consul/api"
	"github.com/hertz-contrib/registry/consul"
	"log"
	"yima_user_app/domain"
)

func main() {

	config := api.DefaultConfig()
	config.Address = "127.0.0.1:8500"
	client, err := api.NewClient(config)
	if err != nil {
		panic(err)
	}
	r := consul.NewConsulRegister(client)
	h := server.Default(
		server.WithHostPorts("127.0.0.1:38000"),
		server.WithRegistry(r, &registry.Info{
			ServiceName: "yima.demo.user",
			Addr:        utils.NewNetAddr("tcp", "127.0.0.1:38000"),
			Weight:      1,
			Tags:        nil,
		}),
	)

	register(h)
	h.Spin()

	k := yimademouser.NewServer(
		new(domain.YimaDemoUserImpl),
		kserver.WithRegistryInfo(&registry2.Info{
			ServiceName: "yima.demo.news",
			Addr:        utils.NewNetAddr("tcp", "127.0.0.1:8889"),
			Weight:      1,
		}),
		// 绑定到内网ip以便consul服务发现
		kserver.WithServiceAddr(utils.NewNetAddr("tcp", "127.0.0.1:8889")))
	err = k.Run()
	if err != nil {
		log.Println(err.Error())
	}
}
