// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSciNews = "sci_news"

// SciNews mapped from table <sci_news>
type SciNews struct {
	ID        string    `gorm:"column:id;primaryKey;comment:新闻ID" json:"id"`                                         // 新闻ID
	Title     string    `gorm:"column:title;not null;comment:新闻标题" json:"title"`                                     // 新闻标题
	Type      string    `gorm:"column:type;not null;comment:新闻类型" json:"type"`                                       // 新闻类型
	UserID    string    `gorm:"column:user_id;not null;comment:作者ID" json:"user_id"`                                 // 作者ID
	Link      string    `gorm:"column:link;comment:新闻链接" json:"link"`                                                // 新闻链接
	Cover     string    `gorm:"column:cover;not null;comment:新闻封面链接" json:"cover"`                                   // 新闻封面链接
	Downloads int32     `gorm:"column:downloads;not null;comment:下载量" json:"downloads"`                              // 下载量
	GmtCreate time.Time `gorm:"column:gmt_create;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"gmt_create"` // 创建时间
	CreateBy  string    `gorm:"column:create_by;not null;comment:创建操作人" json:"create_by"`                            // 创建操作人
	GmtUpdate time.Time `gorm:"column:gmt_update;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"gmt_update"` // 更新时间
	UpdateBy  string    `gorm:"column:update_by;not null;comment:更新操作人" json:"update_by"`                            // 更新操作人
}

// TableName SciNews's table name
func (*SciNews) TableName() string {
	return TableNameSciNews
}
