// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	ID        string    `gorm:"column:id;primaryKey;comment:用户ID" json:"id"`                                         // 用户ID
	Nickname  string    `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                                 // 昵称
	Phone     string    `gorm:"column:phone;not null;comment:手机号" json:"phone"`                                      // 手机号
	Email     string    `gorm:"column:email;not null;comment:邮箱" json:"email"`                                       // 邮箱
	Password  string    `gorm:"column:password;comment:密码" json:"password"`                                          // 密码
	Salt      string    `gorm:"column:salt;comment:盐值" json:"salt"`                                                  // 盐值
	GmtCreate time.Time `gorm:"column:gmt_create;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"gmt_create"` // 创建时间
	GmtUpdate time.Time `gorm:"column:gmt_update;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"gmt_update"` // 更新时间
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
