// Code generated by Kitex v0.7.1. DO NOT EDIT.

package yimanews

import (
	server "github.com/cloudwego/kitex/server"
	news "yima_user_app/kitex_gen/yima/news"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler news.YimaNews, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
